//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RacingHubCarRental
{
    using System;
    using System.Collections.Generic;

    public partial class CarModel
    {
        /// <summary>
        /// Creates a new instance of <see cref="CarModel"/> with initialized collections.
        /// </summary>
        public CarModel()
        {
            FleetCars = new HashSet<FleetCar>();
        }

        public int CarModelID { get; set; }
        public int ManufacturerModelID { get; set; }
        public int ProductionYear { get; set; }

        /// <summary>
        /// Indicates whether this model uses manual transmission.
        /// </summary>
        public bool IsManualGear { get; set; }

        // ---------------------------------------------------------------------
        // Pricing & Billing
        // ---------------------------------------------------------------------

        /// <summary>
        /// Standard daily rental price for this model.
        /// </summary>
        public decimal DailyPrice { get; set; }

        /// <summary>
        /// Penalty price applied per delayed day during late returns.
        /// </summary>
        public decimal DayDelayPrice { get; set; }
        public decimal DayIncomePrice { get; set; }

        public virtual ManufacturerModel ManufacturerModel { get; set; }
        
    }
}

