//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RacingHubCarRental
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    /// <summary>
    /// Represents a single car in the fleet.
    /// </summary>
    public partial class FleetCar
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="FleetCar"/> class.
        /// </summary>
        public FleetCar()
        {
            Rentals = new HashSet<Rental>();
            IsProper = true; // Default to proper
            CurrentMileage = 0; // Default mileage
        }

        /// <summary>
        /// Gets or sets the license plate number of the car.
        /// </summary>
        [Key]
        [Required]
        [StringLength(20)]
        [Display(Name = "License Plate")]
        public string LicensePlate { get; set; }

        /// <summary>
        /// Gets or sets the associated CarModel ID.
        /// </summary>
        [Required]
        public int CarModelID { get; set; }

        /// <summary>
        /// Gets or sets the current mileage of the car.
        /// </summary>
        [Display(Name = "Current Mileage (km)")]
        [Range(0, int.MaxValue, ErrorMessage = "Mileage must be a positive number.")]
        public int CurrentMileage { get; set; }

        /// <summary>
        /// Gets or sets the image URL or path of the car.
        /// </summary>
        [StringLength(250)]
        [Display(Name = "Car Image")]
        public string CarImage { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether the car is in proper condition.
        /// </summary>
        [Display(Name = "Proper Condition")]
        public bool IsProper { get; set; }

        /// <summary>
        /// Navigation property to the associated CarModel.
        /// </summary>
        public virtual CarModel CarModel { get; set; }

        /// <summary>
        /// Navigation property to the collection of rentals for this car.
        /// </summary>
        public virtual ICollection<Rental> Rentals { get; set; }
    }
}

