//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RacingHubCarRental
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    /// <summary>
    /// Represents a car manufacturer.
    /// </summary>
    public partial class Manufacturer
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Manufacturer"/> class.
        /// </summary>
        public Manufacturer()
        {
            ManufacturerModels = new HashSet<ManufacturerModel>();
        }

        /// <summary>
        /// Gets or sets the unique identifier for the manufacturer.
        /// </summary>
        [Key]
        [Display(Name = "Manufacturer ID")]
        public int ManufacturerID { get; set; }

        /// <summary>
        /// Gets or sets the name of the manufacturer.
        /// </summary>
        [Required(ErrorMessage = "Manufacturer name is required.")]
        [StringLength(100, ErrorMessage = "Manufacturer name cannot exceed 100 characters.")]
        [Display(Name = "Manufacturer Name")]
        public string ManufacturerName { get; set; }

        /// <summary>
        /// Navigation property to the collection of models for this manufacturer.
        /// </summary>
        public virtual ICollection<ManufacturerModel> ManufacturerModels { get; set; }
    }
}

