//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace RacingHubCarRental; // Changed to file-scoped namespace (C# 10)

public partial class Rental
{
    // Properties using simplified syntax (get; set;)
    public int RentalID { get; set; }
    public string LicensePlate { get; set; }
    public int UserID { get; set; }
    public DateTime PickUpDate { get; set; }
    public DateTime ReturnDate { get; set; }
    public DateTime? ActualReturnDate { get; set; } // Nullable simplified using '?'

    // Navigation Properties
    public virtual FleetCar FleetCar { get; set; }
    public virtual User User { get; set; }
}
